on:
  release:
    types: [created]

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Changelog
        id: changelog
        uses: infocus7/changelog-files-action@65a15c5cb271b3ded5dd2577cbf880a48203a6b4
        with:
          changelog-directory: 'changelogs-fun'
          release-tag-name: ${{ github.ref_name }}
      - name: Update Release Notes
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            repoOwner="${{ github.repository_owner }}"
            repoName="${{ github.repository }}"
            const releaseId = ${{ github.event.release.id }};
            const changelog = ${{ steps.changelog.outputs.changelog }};
            curl -X PATCH \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $github-token" \
              "https://api.github.com/repos/$repoOwner/$repoName/releases/$releaseId" \
              -d "$changelog"
